# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "CLI for interacting with Targetprocess"
  homepage "https://github.com/lifedraft/targetprocess-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.2.0/tp_darwin_amd64.tar.gz"
      sha256 "e6423f851bb4b7e988b534c6d83ef9dd26df47b66d436836b4a8e14a5848b521"

      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.2.0/tp_darwin_arm64.tar.gz"
      sha256 "935b124667485fd47332167449240c128799a16940ca365d0bc51507c2ca55d0"

      def install
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.2.0/tp_linux_amd64.tar.gz"
      sha256 "83bea5734fb921f6b768cdd8f1cf9f1d98d68a19cda94c224f41657cc817468a"
      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.2.0/tp_linux_arm64.tar.gz"
      sha256 "e360fd4d5ec21a30daac20e29cde31afa806b2e33dc176d5eb6bbbf2d0e3f764"
      def install
        bin.install "tp"
      end
    end
  end

  test do
    system "#{bin}/tp", "--version"
  end
end
