# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "CLI for interacting with Targetprocess"
  homepage "https://github.com/lifedraft/targetprocess-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.5.0/tp_darwin_amd64.tar.gz"
      sha256 "4e1156e542b09a4967a0c34dcd9417ef25dbea3bcdb877a220f897563d382388"

      define_method(:install) do
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.5.0/tp_darwin_arm64.tar.gz"
      sha256 "a8dd53d4af2a593ea8578ffa14a24b057779783593f87aca7ac00f77f2cae663"

      define_method(:install) do
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.5.0/tp_linux_amd64.tar.gz"
      sha256 "5a04ae9d3f6c5ad9c69c262e3b4f8e0f40ca81b2359c7db10a5412add8572da7"
      define_method(:install) do
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.5.0/tp_linux_arm64.tar.gz"
      sha256 "f088f2f8921def384262f4564183b4ec537537de006d29d385521816cde34b36"
      define_method(:install) do
        bin.install "tp"
      end
    end
  end

  test do
    system "#{bin}/tp", "--version"
  end
end
