# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "CLI for interacting with Targetprocess"
  homepage "https://github.com/lifedraft/targetprocess-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.3.0/tp_darwin_amd64.tar.gz"
      sha256 "8ce2fb42db3ac86351c39dec30e45a4afa0b4304414d76107c7be3236150167b"

      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.3.0/tp_darwin_arm64.tar.gz"
      sha256 "89c09b47348db9afcd669d7eb4a1b788fea509a2e2da392d8a5866447b1c9edd"

      def install
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.3.0/tp_linux_amd64.tar.gz"
      sha256 "ec090dc18e7d9af3ef90589b04bc7c1871846e2f898aa7612342c2bc14945639"
      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lifedraft/targetprocess-cli/releases/download/v0.3.0/tp_linux_arm64.tar.gz"
      sha256 "9ebceeb68d1851228bf83c16febe72d7d96052b3888942a6d75e06e4f4f98002"
      def install
        bin.install "tp"
      end
    end
  end

  test do
    system "#{bin}/tp", "--version"
  end
end
